pipeline {
    agent {
        docker {
            image 'maven:3-jdk-13'
        }
    }
    stages {
        stage('Smoke') {
            steps {
                sh "mvn clean verify -Dtags='type:Smoke'"
                publishHTML (target: [
                        reportDir: 'target/site/serenity',
                        reportFiles: 'index.html',
                        reportName: "Smoke tests report"
                ])
            }
        }
        stage('API') {
            steps {
                sh "mvn clean verify -Dtags='type:API'"
                publishHTML (target: [
                        reportDir: 'target/site/serenity',
                        reportFiles: 'index.html',
                        reportName: "API tests report"
                ])
            }
        }
        stage('Results') {
            steps {
                junit '**/target/failsafe-reports/*.xml'
            }
        }
        stage('Integration tests') {
            steps {
                build job: 'loan-integration-tests', parameters: [ string(name: 'environment', value:'stg')]
            }
        }
    }
}
