pipeline {
    agents {
        agent {
            docker {
                image 'openjdk:13-alpine'
            }
        }
        agent {
            docker {
                image 'maven:3-alpine'
                args '-v /root/.m2:/root/.m2'
            }
        }
    }
    stages {
        stage('Git checkout') { // for display purposes
            steps {
                git 'https://github.com/mmatlakhov/e2e-automation-pipeline.git'
            }
        }
        stage('Smoke') {
            steps {
                sh "mvn clean verify -Dtags='type:Smoke'"
                publishHTML (target: [
                        reportDir: 'target/site/serenity',
                        reportFiles: 'index.html',
                        reportName: "Smoke tests report"
                ])
            }
        }
        stage('API') {
            steps {
                sh "mvn clean verify -Dtags='type:API'"
                publishHTML (target: [
                        reportDir: 'target/site/serenity',
                        reportFiles: 'index.html',
                        reportName: "API tests report"
                ])
            }
        }
        stage('Results') {
            steps {
                junit '**/target/failsafe-reports/*.xml'
            }
        }
    }
}
